# Generated by Django 5.0.3 on 2024-04-09 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_blog_author_email_author_name_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='authors',
            field=models.ManyToManyField(null=True, to='catalog.author'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='body_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='mod_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='number_of_comments',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='number_of_pingbacks',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pub_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='rating',
            field=models.IntegerField(default=5, null=True),
        ),
    ]
